# @package _group_
# Decays the learning rate of each parameter group by gamma every step_size epochs.
name: step

# Period of learning rate decay.
step_size: 30

# Multiplicative factor of learning rate decay.
gamma: 0.1
