# @package _group_
name: standard

early_stopping:
  monitor: "Val/mIoU"
  min_delta: 0.0005
  patience: 10
  mode: "max"
  verbose: false

checkpoints:
  filename: "best" # PL Default: "{epoch}-{step}". `=` in filename can cause errors when parsing cli overrides.
  save_last: true
  save_top_k: 1
  monitor: "Val/mIoU"
  mode: "max"
  period: 10
  verbose: false

log_media:
  max_samples: 10
  period_epoch: 1
  period_step: 0
  save_to_disk: true
  save_latest_only: true
  verbose: true

lr_monitor:
  # set to epoch or step to log lr of all optimizers at the same interval, set to None to log at individual
  # interval according to the interval key of each scheduler.
  logging_interval: "step"
  log_momentum: false # If true, log the momentum values of the optimizer, if present
